sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '6'
  - '4'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run test-travis
after_success:
  - npm install coveralls@2.11.9 && cat ./coverage/lcov.info | coveralls"
env: NODE_ENV=test
